services:

  postgres_bingle:
    image: postgres:13
    container_name: bingle_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  bingle_bot:
    container_name: binglebot3
    image: binglebot3:latest
    restart: unless-stopped
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
    depends_on:
      postgres_bingle:
        condition: service_healthy
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: