version: "3.8"
services:

  postgres_bingle:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bingle:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bingle_network

  bingle_bot:
    container_name: binglebot3
    image: binglebot3:latest
    restart: unless-stopped
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bingle_network


networks:
  bingle_network:
    driver: bridge

volumes:
  postgres_data_bingle: