version: "3.8"
services:
  telegram_bot:
    container_name: binglebot3
    image: binglebot3:latest
    restart: unless-stopped
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_ADMIN_IDS: ${TG_BOT_ADMIN_IDS}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
